### ISSUE TITLE
Provide examples of Harvester Worker and Messenger plugins

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/Harvester-NGE#2]

**Comment by DanilaOleynik** [comment]
Hello, 

I had checked code and documentation for messenger plugins: 
Here is short description of current functionality: 
https://github.com/PanDAWMS/panda-harvester/wiki/Plugins-and-Agents-descriptions#shared-file-messenger

Here is the source code of plugin: 
https://github.com/PanDAWMS/panda-harvester/blob/master/pandaharvester/harvestermessenger/shared_file_messenger.py

But, it looks like server component...  So - main question is format of messages, which should be produced by 'worker'.

**Comment by mturilli** [comment]
* Get an example of a job description
* Produce an example about integration and how to get the plugin enabled
  * Deploy a harvester on `two.radical-project.org`
    * Creating a login for Danila on `two.radical-project.org`
